name: Update RSS Feeds

on:
  schedule:
    - cron: '0 0 * * *'  # Spouští se každý den v půlnoci
  workflow_dispatch:   # Umožňuje ruční spuštění

jobs:
  update-feeds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml

    - name: Run update script
      run: python crawl_and_generate_feed.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add jogadnes.xml
        git commit -m "Automatická aktualizace RSS feedu"
        git push
