name: Update jogadnes XML feed

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: python -m pip install requests beautifulsoup4 lxml

      - name: Generate feed from crawler
        run: python tools/crawl_and_generate_feed.py

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep -q jogadnes.xml; then
            git add jogadnes.xml
            git commit -m "Auto-update jogadnes.xml"
            git push
          else
            echo "No changes to jogadnes.xml"
